### PR TITLE
Changes so the module can be easily used when imported

### PR DESCRIPTION
**Pull request by ArielMAJ**
- [X] Documentation update
- [ ] Bug fix
- [X] New feature
- [X] Other, please explain:

### What changes did you make? (Give an overview)
1. Changed tabs to spaces in `__init__.py`.
2. Added some new lines to a few of the docstrings in `__init__.py`.
3. Created a new main function at the top of `__init__.py`.
4. Old main function is now called "run" and receives all the same arguments as expected from CLI with the same default values. 
    - This means the user can now import waifu2x and just run `waifu2x.run(input_img_path="./input.png", output_img_path="./output.png")` to upscale images from a script.
    - This also means everything works the same (main function calls run() with default args).
5. Added extra argument to "run" and a few other functions in `__init__.py` as to stop prints from happening (as they might not be wanted when importing this module.

### Which issue (if any) does this pull request address?
Solves #3

### Is there anything you'd like reviewers to focus on?
Test if anything you already have using this package still works normally (it should).

### CODE REVIEW

**Comment by FredHappyface** [comment]
1. Changed tabs to spaces in `__init__.py`.
    - Why? This project uses a styleguide that has been documented, please can you stick to it

Happy to review when the diffs are a little more manageable :)

**Comment by ArielMAJ** [comment]
The main reason here is that I just got used to working with black+pylint and:
     1. black fails to parse the file;
     2. pylint complains about indentation in every single line;
 
I just tried to look for the documentation on the styleguide and couldn't find it. I might see into it later to make as little changes as possible to the styling and force push the new commits.

**Comment by ArielMAJ** [comment]
I've removed the changes to styling from the commits and kept only the essential.

With those changes, upscaling from a script should be as simple as:
```
import waifu2x
waifu2x.run("some_image.jpg")
```
Ofc you can pass in most of the other parameters as well.

I also added the option "should_print", so prints can be suppressed when calling "run" from another script (so those prints don't mess with other program's workflows).

**Comment by FredHappyface** [comment]
Thank you for the PR! Apologies for the delay in approving this

Looks great! And thanks for reverting the style

**Pull request merged**
